name: Test EOPF JupyterHub

on:
  push:
    paths:
        - 'scripts/test_jupyterhub.py'   
  schedule:
    - cron: "*/30 * * * *" 
  workflow_dispatch: 

jobs:
  test-eopf-jupyterhub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Pushgateway env
        run: |
          echo "URL=https://jupyterhub.user.eopf.eodc.eu" >> $GITHUB_ENV
          echo "USER=${{ secrets.EOPF_USER }}" >> $GITHUB_ENV
          echo "TOKEN=${{ secrets.EOPF_TOKEN }}" >> $GITHUB_ENV 
          echo "SERVICE_WS=jupyterhub.user.eopf.eodc.eu" >> $GITHUB_ENV
          echo "PUSHGATEWAY_URL=${{ secrets.PUSHGATEWAY_ENDPOINT }}" >> $GITHUB_ENV
          echo "PUSHGATEWAY_USERNAME=${{ secrets.PUSHGATEWAY_USERNAME }}" >> $GITHUB_ENV
          echo "PUSHGATEWAY_PASSWORD=${{ secrets.PUSHGATEWAY_PASSWORD }}" >> $GITHUB_ENV

      - name: Test EOPF JupyterHub
        run: python scripts/test_jupyter.py
